FROM rabbitmq:management

ENV TZ=Asia/Shanghai

ENV RABBITMQ_DEFAULT_USER=admin 
ENV RABBITMQ_DEFAULT_PASS=admin 
# RUN rabbitmqctl add_user admin admin \
# && rabbitmqctl set_user_tags admin administrator\


# RUN netstat -ano | grep 5672
# RUN rabbitmqctl  set_permissions -p "/" admin '.*' '.*' '.*'

