FROM jupyter/base-notebook
MAINTAINER yutiansut 'yutiansut@qq.com'


# 修改docker的时区
RUN apt update \
    && apt install tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime \
    && apt install python3-tk \
    && pip install pip -U -i https://pypi.doubanio.com/simple \
    && pip install -r https://raw.githubusercontent.com/yutiansut/QUANTAXIS/master/requirements.txt -i https://pypi.doubanio.com/simple \
    && pip install tushare \
    && pip install pytdx \
    && pip install quantaxis



EXPOSE 8888
