/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.QA_Market_order');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.QA_Market_order = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.QA_Market_order, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.QA_Market_order.displayName = 'proto.QA_Market_order';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.QA_Market_order.prototype.toObject = function(opt_includeInstance) {
  return proto.QA_Market_order.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.QA_Market_order} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QA_Market_order.toObject = function(includeInstance, msg) {
  var f, obj = {
    price: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    date: jspb.Message.getFieldWithDefault(msg, 2, ""),
    datetime: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sendingTime: jspb.Message.getFieldWithDefault(msg, 4, ""),
    transactTime: jspb.Message.getFieldWithDefault(msg, 5, ""),
    amount: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    towards: jspb.Message.getFieldWithDefault(msg, 7, 0),
    code: jspb.Message.getFieldWithDefault(msg, 8, ""),
    user: jspb.Message.getFieldWithDefault(msg, 9, ""),
    strategy: jspb.Message.getFieldWithDefault(msg, 10, ""),
    type: jspb.Message.getFieldWithDefault(msg, 11, ""),
    bidModel: jspb.Message.getFieldWithDefault(msg, 12, ""),
    amountModel: jspb.Message.getFieldWithDefault(msg, 13, ""),
    orderId: jspb.Message.getFieldWithDefault(msg, 14, ""),
    tradeId: jspb.Message.getFieldWithDefault(msg, 15, ""),
    status: jspb.Message.getFieldWithDefault(msg, 16, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.QA_Market_order}
 */
proto.QA_Market_order.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.QA_Market_order;
  return proto.QA_Market_order.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.QA_Market_order} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.QA_Market_order}
 */
proto.QA_Market_order.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatetime(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendingTime(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactTime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAmount(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTowards(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrategy(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setBidModel(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setAmountModel(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setTradeId(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.QA_Market_order.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.QA_Market_order.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.QA_Market_order} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QA_Market_order.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatetime();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSendingTime();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTransactTime();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getTowards();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getStrategy();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getBidModel();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getAmountModel();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getTradeId();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
};


/**
 * optional float price = 1;
 * @return {number}
 */
proto.QA_Market_order.prototype.getPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.QA_Market_order.prototype.setPrice = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string date = 2;
 * @return {string}
 */
proto.QA_Market_order.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setDate = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string datetime = 3;
 * @return {string}
 */
proto.QA_Market_order.prototype.getDatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setDatetime = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string sending_time = 4;
 * @return {string}
 */
proto.QA_Market_order.prototype.getSendingTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setSendingTime = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string transact_time = 5;
 * @return {string}
 */
proto.QA_Market_order.prototype.getTransactTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setTransactTime = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional float amount = 6;
 * @return {number}
 */
proto.QA_Market_order.prototype.getAmount = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.QA_Market_order.prototype.setAmount = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional int64 towards = 7;
 * @return {number}
 */
proto.QA_Market_order.prototype.getTowards = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.QA_Market_order.prototype.setTowards = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string code = 8;
 * @return {string}
 */
proto.QA_Market_order.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setCode = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional string user = 9;
 * @return {string}
 */
proto.QA_Market_order.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setUser = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string strategy = 10;
 * @return {string}
 */
proto.QA_Market_order.prototype.getStrategy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setStrategy = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional string type = 11;
 * @return {string}
 */
proto.QA_Market_order.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setType = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional string bid_model = 12;
 * @return {string}
 */
proto.QA_Market_order.prototype.getBidModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setBidModel = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional string amount_model = 13;
 * @return {string}
 */
proto.QA_Market_order.prototype.getAmountModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setAmountModel = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional string order_id = 14;
 * @return {string}
 */
proto.QA_Market_order.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setOrderId = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional string trade_id = 15;
 * @return {string}
 */
proto.QA_Market_order.prototype.getTradeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setTradeId = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional string status = 16;
 * @return {string}
 */
proto.QA_Market_order.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.QA_Market_order.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 16, value);
};


