
# shipane
cn_en_compare = {'明细': 'id',
                 '证券代码': 'code',
                 '证券名称': 'name',
                 '股票余额': 'amount',
                 '可用余额': 'sell_available',
                 '冻结数量': 'frozen',
                 '盈亏': 'pnl',
                 '成本价': 'hold_price',
                 '盈亏比例(%)': 'pnl_ratio',
                 '市价': 'price',
                 '市值': 'market_value',
                 '交易市场': 'SSE',
                 '股东帐户': 'shareholders',
                 '实际数量': 'total_amount',
                 '可申赎数量': 'redemption_number',
                 '资讯': 'message',
                 '汇率': 'exchange_rate',
                 '沪港深港市场': 'hkmarket',
                 '成本价港币': 'hold_price_hk',
                 '买入成本价港币': 'buy_price_hk',
                 '买入在途数量': 'buy_onway',
                 '卖出在途数量': 'sell_onway'}
