#


class per_unit():
    def __init__(self):
        self.unit_table = {
            'P': 10,
            'Y': 10,
            'M': 10,
            'A': 10,
            'B': 10,
            'C': 10,
            'L': 5,
            'JD': 10,
            'J': 100,
            'JM': 60,
            'FB': 500,
            'I': 100,
            'PP': 5,
            'BB': 500,
            'V': 5,
            'CS': 10,
            'EG': 10,
            'AL': 5,
            'AU': 1000,
            'CU': 5,
            'RU': 10,
            'FU': 10,
            'RB': 10,
            'WR': 10,
            'ZN': 5,
            'BU': 10,
            'AG': 15,
            'SN': 1,
            'NI': 1,
            'HC': 10,
            'PB': 5,
            'SP': 10,
            'T': 10000,
            'IC': 200,
            'IH': 300,
            'IF': 300,
            'TF': 10000,
            'TS': 20000,
            'RI': 20,
            'RO': 5,
            'SR': 10,
            'TA': 5,
            'WS': 10,
            'FG': 20,
            'OI': 10,
            'ZC': 100,
            'CF': 5,
            'WT': 10,
            'RM': 10,
            'PM': 10,
            'SM': 5,
            'SF': 5,
            'LR': 20,
            'MA': 10,
            'JR': 20,
            'RS': 10,
            'CY': 5,
            'AP': 10,
        }

    def get(self, code):
        return self.unit_table.get(code[0:-2])


class MARKET_PRESET:

    def __init__(self):
        """
        unit_table 合约乘数
        commission_coeff_peramount 按总量计算手续费系数
        commission_coeff_pervol 按手数计算的手续费系数
        commission_coeff_today_peramount 按总量计算的平今手续费系数
        commission_coeff_today_pervol 按手数计算的平今手续费系数

        多头开仓保证金系数
        空头开仓保证金系数
        """

        self.table = {
                'P': {'name': '棕榈油',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.25,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.06,                              
                'sell_frozen_coeff': '0.06',                           
                'exchange': 'DCE'},                                    
                'Y': {'name': '豆油',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.25,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.06,                              
                'sell_frozen_coeff': '0.06',                           
                'exchange': 'DCE'},                                    
                'M': {'name': '豆粕',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 1.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 0.75,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'A': {'name': '豆一',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'B': {'name': '豆二',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 1.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'C': {'name': '玉米',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 1.2,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 0.6,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'DCE'},                                    
                'L': {'name': '塑料',                                     
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'JD': {'name': '鸡蛋',                                    
                'commission_coeff_peramount': 0.00015,                 
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 0.00015,           
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'DCE'},                                    
                'J': {'name': '焦炭',                                     
                'commission_coeff_peramount': 6e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 0.00018,           
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 100,                                     
                'buy_frozen_coeff': 0.09,                              
                'sell_frozen_coeff': '0.09',                           
                'exchange': 'DCE'},                                    
                'JM': {'name': '焦煤',                                    
                'commission_coeff_peramount': 6e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 0.00018,           
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 60,                                      
                'buy_frozen_coeff': 0.09,                              
                'sell_frozen_coeff': '0.09',                           
                'exchange': 'DCE'},                                    
                'FB': {'name': '纤维板',                                   
                'commission_coeff_peramount': 0.0001,                  
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 500,                                     
                'buy_frozen_coeff': 0.2,                               
                'sell_frozen_coeff': '0.2',                            
                'exchange': 'DCE'},                                    
                'I': {'name': '铁矿石',                                    
                'commission_coeff_peramount': 6e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 6e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 100,                                     
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'DCE'},                                    
                'PP': {'name': '聚丙烯',                                   
                'commission_coeff_peramount': 6e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 3e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'EG': {'name': '乙二醇',                                   
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 4.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.06,                              
                'sell_frozen_coeff': '0.06',                           
                'exchange': 'DCE'},                                    
                'BB': {'name': '胶合板',                                   
                'commission_coeff_peramount': 0.0001,                  
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 500,                                     
                'buy_frozen_coeff': 0.2,                               
                'sell_frozen_coeff': '0.2',                            
                'exchange': 'DCE'},                                    
                'V': {'name': 'PVC',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'DCE'},                                    
                'CS': {'name': '玉米淀粉',                                  
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 1.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 0.75,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'DCE'},                                    
                'AL': {'name': '沪铝',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'SHF'},                                    
                'AU': {'name': '沪金',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 10.0,                       
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 10.0,                 
                'unit_table': 1000,                                    
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'SHF'},                                    
                'CU': {'name': '沪铜',                                    
                'commission_coeff_peramount': 5e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'SHF'},                                    
                'RU': {'name': '橡胶',                                    
                'commission_coeff_peramount': 4.5e-05,                 
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 2.25e-05,          
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.09,                              
                'sell_frozen_coeff': '0.09',                           
                'exchange': 'SHF'},                                    
                'FU': {'name': '燃油',                                    
                'commission_coeff_peramount': 5e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.1,                               
                'sell_frozen_coeff': '0.1',                            
                'exchange': 'SHF'},                                    
                'RB': {'name': '螺纹钢',                                   
                'commission_coeff_peramount': 0.0001,                  
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.09,                              
                'sell_frozen_coeff': '0.09',                           
                'exchange': 'SHF'},                                    
                'WR': {'name': '线材',                                    
                'commission_coeff_peramount': 4e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 4e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'ZN': {'name': '沪锌',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'BU': {'name': '沥青',                                    
                'commission_coeff_peramount': 0.0001,                  
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'AG': {'name': '沪银',                                    
                'commission_coeff_peramount': 5e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 2.5e-05,           
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 15,                                      
                'buy_frozen_coeff': 0.06,                              
                'sell_frozen_coeff': '0.06',                           
                'exchange': 'SHF'},                                    
                'SN': {'name': '沪锡',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 1,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'SHF'},                                    
                'NI': {'name': '沪镍',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 6.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 1,                                       
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'HC': {'name': '热轧卷板',                                  
                'commission_coeff_peramount': 0.0001,                  
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'PB': {'name': '沪铅',                                    
                'commission_coeff_peramount': 4e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 4e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'SHF'},                                    
                'SP': {'name': '纸浆',                                    
                'commission_coeff_peramount': 5e-05,                   
                'commission_coeff_pervol': 0.0,                        
                'commission_coeff_today_peramount': 5e-05,             
                'commission_coeff_today_pervol': 0.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'SHF'},                                    
                'SC': {'name': '原油',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 20.0,                       
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 20.0,                 
                'unit_table': 1000,                                    
                'buy_frozen_coeff': 0.1,                               
                'sell_frozen_coeff': '0.1',                            
                'exchange': 'SHF'},                                    
                'RI': {'name': '早籼稻',                                   
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.5,                  
                'unit_table': 20,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'ZCE'},                                    
                'RS': {'name': '菜油',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.2,                               
                'sell_frozen_coeff': '0.2',                            
                'exchange': 'ZCE'},                                    
                'SR': {'name': '白糖',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.5,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'ZCE'},                                    
                'TA': {'name': 'PTA',                                   
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.5,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'WH': {'name': '强麦',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.25,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.2,                               
                'sell_frozen_coeff': '0.2',                            
                'exchange': 'ZCE'},                                    
                'FG': {'name': '玻璃',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 6.0,                  
                'unit_table': 20,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'OI': {'name': '菜油',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 1.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'ZC': {'name': '菜籽',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 4.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 4.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.08,                              
                'sell_frozen_coeff': '0.08',                           
                'exchange': 'ZCE'},                                    
                'CF': {'name': '郑棉',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 4.3,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.15,                 
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'RM': {'name': '菜粕',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 1.5,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 0.75,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.06,                              
                'sell_frozen_coeff': '0.06',                           
                'exchange': 'ZCE'},                                    
                'PM': {'name': '普麦',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 5.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 5.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'ZCE'},                                    
                'SM': {'name': '锰硅',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 6.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'SF': {'name': '硅铁',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 9.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'LR': {'name': '晚籼稻',                                   
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 20,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'ZCE'},                                    
                'MA': {'name': '甲醇',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 2.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 6.0,                  
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.07,                              
                'sell_frozen_coeff': '0.07',                           
                'exchange': 'ZCE'},                                    
                'JR': {'name': '粳稻',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 3.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 3.0,                  
                'unit_table': 20,                                      
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.05',                           
                'exchange': 'ZCE'},                                    
                'CY': {'name': '棉纱',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 4.0,                        
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 2.0,                  
                'unit_table': 5,                                       
                'buy_frozen_coeff': 0.05,                              
                'sell_frozen_coeff': '0.0.5',                          
                'exchange': 'ZCE'},                                    
                'AP': {'name': '苹果',                                    
                'commission_coeff_peramount': 0.0,                     
                'commission_coeff_pervol': 20.0,                       
                'commission_coeff_today_peramount': 0.0,               
                'commission_coeff_today_pervol': 20.0,                 
                'unit_table': 10,                                      
                'buy_frozen_coeff': 0.2,                               
                'sell_frozen_coeff': '0.2',                            
                'exchange': 'ZCE'}}                                    
                                                         
    # 手续费比例
    def get_commission_coeff(self, code, dtype):
        pass

    # 印花税系数
    def get_tax_coeff(self, code, dtype):
        pass

    # 交易时间
    def get_trade_time(self, code, dtype):
        pass

    # 交易日期
    def get_trade_day(self, code, dtype):
        pass

    # 交易规则( t0/sell_open)
    def get_trade_rules(self, code, dtypes):
        pass

    # 交易杠杆
    def get_trade_margin(self, code, dtypes):
        pass
